---
version: "2"

plugins:
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        typescript:
        javascript:
        python:
          python_version: 3
  eslint:
    enabled: true
    channel: "eslint-8"
    config:
      config: .eslintrc
  fixme:
    enabled: true
  shellcheck:
    enabled: true

exclude_patterns:
  - "**.md"
  - "**.txt"
  - "**.json"
  - docs/
  - script/
  - "**/api/"
  - "**/build/"
  - "**/coverage/"
  - "**/dist/"
  - "**/node_modules/"
  - "**/public/"
  - "**/script/"
  - client/config/
  - servers/lib/src/types.ts
