---
version: "2"
plugins:
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
        typescript:
        javascript:
        python:
          python_version: 3
  eslint:
    enabled: true
    channel: "eslint-8"
    config:
      config: .eslintrc
  fixme:
    enabled: true
  identical-code:
    config:
      threshold: 55
  shellcheck:
    enabled: true
  similar-code:
    config:
      threshold: 55
exclude_patterns:
  - "**.md"
  - "**.txt"
  - "**.json"
  - docs/
  - "**/node_modules/"
  - "**/build/"
  - "**/public/"
  - "**/coverage"
  - "client/config/"
