yaml-files:
  - '*.yaml'
  - '*.yml'
  - '.yamllint'

ignore: |
  deploy/workspace/kubernetes/keycloak/production/manifests/crds/

extends: default

rules:
  document-start:
    present: false
  line-length:
    max: 120
  truthy:
    allowed-values: ['TRUE', 'True', 'true', 'FALSE', 'False', 'false']
    check-keys: true
