site_name: Digital Twin as a Service (DTaaS)

nav:
  - Home: index.md
  - Admin:
      - website: admin/client/CLIENT.md
      - library microservice: admin/servers/lib/LIB-MS.md
  - User:
      - Features: user/features.md
      - Website: user/website/index.md
      - Library: 
          - Assets: user/servers/lib/assets.md
          - Microservice: user/servers/lib/LIB-MS.md
      - Examples: user/examples/index.md
  - FAQ: FAQ.md
  - Bugs: bugs.md

use_directory_urls: false

theme: 
  name: material
  locale: en
  
extra_css:
  - docs/css/extra.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
  - pymdownx.highlight:
      linenums: true
      use_pygments: true
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets      
  - pymdownx.superfences
  - pymdownx.details
  - mdx_math:
      enable_dollar_delimiter: True