site_name: Digital Twin as a Service

nav:
  - Home: index.md
  - Admin:
      - website: admin/client/CLIENT.md
  - User:
      - Examples: user/examples/incubator/README.md
      - Lib Microservice: user/servers/lib/LIB-MS.md

theme: 
  name: material
  locale: en
  highlightjs: true
  
extra_css:
  - docs/css/extra.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - mdx_math:
      enable_dollar_delimiter: True