site_name: Digital Twin as a Service

theme: 
  name: material
  locale: en
  highlightjs: true
  
extra_css:
  - docs/css/extra.css

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
