apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: traefik-dtaas-workspace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: traefik-dtaas-workspace
subjects:
  - kind: ServiceAccount
    name: traefik
    namespace: dtaas-workspace
