apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: dtaas-workspace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:26.0.7
          args:
            - "start"
            - "--proxy-headers=xforwarded"
            - "--hostname-strict=false"
            - "--http-relative-path=/auth"
          env:
            - name: KEYCLOAK_ADMIN
              valueFrom:
                secretKeyRef:
                  name: dtaas-keycloak
                  key: KEYCLOAK_ADMIN
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: dtaas-keycloak
                  key: KEYCLOAK_ADMIN_PASSWORD
            - name: KC_HOSTNAME_STRICT
              value: "false"
            - name: KC_PROXY_HEADERS
              value: xforwarded
            - name: KC_HTTP_ENABLED
              value: "true"
            - name: KC_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  name: dtaas-config
                  key: SERVER_DNS
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
          ports:
            - containerPort: 8080
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 10
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 10
            failureThreshold: 10
          volumeMounts:
            - name: keycloak-data
              mountPath: /opt/keycloak/data
      volumes:
        - name: keycloak-data
          persistentVolumeClaim:
            claimName: keycloak-data
