apiVersion: v1
kind: Service
metadata:
  name: custom-dns
  namespace: dtaas-workspace
  labels:
    app: custom-dns
spec:
  selector:
    app: custom-dns
  ports:
    - name: dns-udp
      port: 53
      protocol: UDP
      targetPort: 53
  type: ClusterIP
