http:
  routers:
    dtaas:
      entryPoints:
        - http
      rule: 'Host(`localhost`)'
      middlewares:
        - basic-auth
      service: dtaas

    user1:
      entryPoints:
        - http
      rule: 'Host(`localhost`) && PathPrefix(`/user1`)'
      middlewares:
        - basic-auth
      service: user1


  # Middleware: Basic authentication
  middlewares:
    basic-auth:
      basicAuth:
        usersFile: "/etc/traefik/auth"


  services:
    dtaas:
      loadBalancer:
        servers:
          - url: "http://localhost:4000"

    user1:
      loadBalancer:
        servers:
          - url: "http://localhost:8090"

