apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: workspace-user1
  namespace: dtaas-workspace
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
