name: Build documentation

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  client:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run the linting checks
        run: |
          printf "docs generate"

      - name: Run the linting checks
        run: |
          printf "docs generate 2nd statement"
